### ISSUE TITLE
Scales display is wrong

### ISSUE THREAD

**Issue by cbenz** [openfisca/legislation-explorer#1]
The thresholds are inverted, they define start values, not end.

http://legislation.openfisca.fr/parameters/ir.bareme

**Comment by benjello** [comment]
Indeed

**Comment by benjello** [comment]
@cbenz : this annoying bug is still there. Should be fixed before hackathon ;-)

**Comment by cbenz** [comment]
@benjello It is now OK, right?

**Comment by benjello** [comment]
@cbenz : Nope. the thresholds should be shifted to arrive to this [result](http://www.journaldunet.com/patrimoine/finances-personnelles/1151203-impot-sur-le-revenu/)

**Comment by benjello** [comment]
@cbenz : do not forget this issue which is very annoying.

**Comment by benjello** [comment]
Thanks !
