### ISSUE TITLE
Missing caller variables (with dated variables)

### ISSUE THREAD

**Issue by cbenz** [openfisca/legislation-explorer#10]
The formula [`rsa_base_ressources`](http://legislation.openfisca.fr/variables/rsa_base_ressources) calls the formula [`rsa_base_ressources_individu`](http://legislation.openfisca.fr/variables/rsa_base_ressources_individu).

But `rsa_base_ressources` does not appear in the caller variables ("variables appelantes" in french) of `rsa_base_ressources_individu`.

It is very probably due to the fact that `rsa_base_ressources` is a `DatedVariable`.

**Comment by benjello** [comment]
[Names have changed](https://github.com/openfisca/openfisca-france/compare/3bba391b94...26653e5517), *_i becomes *_individus.

**Comment by cbenz** [comment]
Yes I mentioned the names of the version deployed online. I think the bug will be the same with the new names :)

BTW I updated the online version, and the description of the issue.

**Comment by benjello** [comment]
Seems ok now. Should we close this issue @cbenz ?

**Comment by cbenz** [comment]
I was waiting to finish everything before wiping issues. But yes, it's fixed.
