### ISSUE TITLE
Can't access source code

### ISSUE THREAD

**Issue by guillett** [openfisca/legislation-explorer#107]
Hi !

Tools you are providing are great ! 👏

Many thanks !

On https://legislation.openfisca.fr/tns_auto_entrepreneur_chiffre_affaires, I expected to be able to go to the source code but the link "[Modifier ces informations](https://legislation.openfisca.fr/UNKNOWN/blob/18.6.0/openfisca_france/model/revenus/activite/non_salarie.py#L1464-L1469)" is not working.

The additional link _Donnée brute au format JSON_ is not working either.

Hope that helps.

**Comment by fpagnoux** [comment]
Hi @guillett,

Thanks for reporting the issue! An abusive massive renaming broke the metadata about `openfisca-france`, causing this line to break 😬.

We'll publish a fix very soon.
