### ISSUE TITLE
Links to variables source code in GitHub are wrong

### ISSUE THREAD

**Issue by edarin** [openfisca/legislation-explorer#11]
Example: go to http://legislation.openfisca.fr/variables/ppa and click on "GitHub" beside the source code of the variable

**Comment by laem** [comment]
Il me semble qu'au premier chargement de la page, le lien est bon. 
Ensuite, vient une mise à jour et notamment la coloration syntaxique de la fonction, et là il est remplacé par un lien erroné.

**Comment by cbenz** [comment]
bien vu

**Comment by benjello** [comment]
Still buggy !

**Comment by cbenz** [comment]
Blocked by https://github.com/openfisca/openfisca-web-api/pull/67

**Comment by cbenz** [comment]
@benjello assigned cbenz and clems 39 minutes ago, why clems?

**Comment by benjello** [comment]
Corrected ;-)

**Comment by cbenz** [comment]
This time it's ok
