### ISSUE TITLE
Add editorial content on a variable

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/legislation-explorer#124]
As a variable maintainer, I can document useful information about a variable.
As a user of a tax and benefit information, I can know more precisely what is a variable, and how I can use it.

---

The legislation explorer extracts a lot of useful information from variables. However, we may want to keep and expose useful information that are not automatically extractible.

For instance:

- What are the typical input variables we should provide to compute a variable.
- For which period do they need to be specified
- Tricks about  the use of this variable ? (for instance, `loyer` is defined for a Menage but always used for a Famille. A line about how to easily cast it may help formula writers).

**Comment by MattiSG** [comment]
Strong agree. This should be provided for parameters as well, would it be only for uniformity.

Would you recommend this to be a new property like `description`, or should we just use Python's heredoc (`'''`) format? Heredoc are less common, but they allow for multiline, and are already used in Entities.

**Comment by sandcha** [comment]
I agree with the need of multiline documentation for variables and parameters.
> In Tunisia for example, we need some place to document evolutions on minimal wages parameters.

As for the best way to make this possible, @guillett @benjello would you recommend a property/ multiple properties/heredoc/...? I remember a _studieuse_ meeting where we spoke about adding more information to legislation explorer pages.
