### ISSUE TITLE
Some nodes are empty in variables tree view

### ISSUE THREAD

**Issue by edarin** [openfisca/legislation-explorer#13]
In https://legislation.openfisca.fr/variables the node `aefa.py` is empty.

This should be because https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/minima_sociaux/aefa.py contains only a dated variable.

**Comment by benjello** [comment]
Nice catch ;-)
I open another issue (#14) to improve  the [variable explorer](https://legislation.openfisca.fr/variables)
