### ISSUE TITLE
Frozen page on api internal server error

### ISSUE THREAD

**Issue by sandcha** [openfisca/legislation-explorer#136]
When I search for `https://legislation.openfisca.fr/paje_cmg`, the page stays on `Chargement des valeurs…`.

We could give more information to the user as on this peculiar context, an API call to this variable `https://fr.openfisca.org/api/v20/variable/paje_cmg` gives: 
```
{
  "error": "Internal server error: 'ascii' codec can't decode byte 0xc3 in position 112: ordinal not in range(128)"
}
```

**Comment by fpalluel** [comment]
Hello, 
Same problem here, when trying to access 'cmu-c' and 'ppa'...

**Comment by fpagnoux** [comment]
This issue seems to have been solved

**Comment by MattiSG** [comment]
No, see for example http://nz.openfisca.org/rates_rebate.
This happens anytime the app has not been rebuilt and the connected API has changed, which can be quite often!

**Comment by fpagnoux** [comment]
Ok, the underlying issue with the French API has been fixed, but the fact that the legislation explorer sucks at explaining what's going on in case of error hasn't been, thanks!
