### ISSUE TITLE
Add a "label" to modules containing variables to improve the legislation explorer

### ISSUE THREAD

**Issue by benjello** [openfisca/legislation-explorer#14]
It would be nice to have a clear label instead of `aefa.py` etc in the [variables explorer](https://legislation.openfisca.fr/variables).

What is the better way to obtain that ?
Should we add a label variable in all the modules containing variables ?

**Comment by edarin** [comment]
I'm working on the code of legislation-explorer, but I didn't get your point ...

**Comment by benjello** [comment]
Instead of having `mesures.py`, `demographie.py` as headers in the variable tree we could have
Mesures, Démographie etc.

**Comment by pnbt** [comment]
Bonne idée. Je regarde avec Christophe comment faire ça au mieux.

Le 30 août 2016 14:11, "Mahdi Ben Jelloul" <notifications@github.com> a
écrit :

**Comment by edarin** [comment]
je ne sais pas parce qu'en vrai ça se refère directement aux modules et sous-modules ce qui est bien pratique dans les recherches quand tu ne connais pas à la base les différents modules ...
(je parle de mon cas)

**Comment by cbenz** [comment]
- [ ] Put a docstring at the head of each module and/or sub-module (@edarin, @benjello)
- [ ] Modify the `/variables` endpoint of the Web API to return the docstring of the module (@cbenz)
- [ ] Modify the `/variables` page of Legislation Explorer to display the docstring foreach module and/or sub-module

@edarin We can have both: keep the `.py` name and display a docstring

**Comment by edarin** [comment]
yeah i was thinking about it

**Comment by MattiSG** [comment]
Low priority. Will reopen if an opportunity arises, but we're not expecting to work on that in the coming weeks.
