### ISSUE TITLE
Load http://openfisca.org/img/logo-openfisca.svg over HTTPS

### ISSUE THREAD

**Issue by guillett** [openfisca/legislation-explorer#142]
Currently some content on https://fr.openfisca.org/legislation/ is loaded via HTTP instead of HTTPS.

To get a green lock next to the URL everything should be loaded via HTTPS.

**Comment by maukoquiroga** [comment]
Hi @guillett, thanks for reporting this issue. There's currently a discussion about this at https://github.com/openfisca/openfisca.org/issues/30 for you to take a look at to.

**Comment by MattiSG** [comment]
@guillett  ![screen shot 2018-05-19 at 15 10 15](https://user-images.githubusercontent.com/222463/40264393-c479610e-5b76-11e8-9a30-dbfb2ced3a54.png)
 🎉 😉
