### ISSUE TITLE
Show more information while variable or parameter loads

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#158]
If I click on a parameter or a variable, I am currently redirected to a blank page with a loading indicator until the API responds.

This is not resilient (see #136) and not a good UX.

We should at least display the “go back to the other X variables and parameters” button immediately, and could also pre-populate the name and description with data as we already have them from the previous page.

**Comment by Morendil** [comment]
This has been improved (#187), perhaps enough that we can close.
