### ISSUE TITLE
Page keeps scroll position upon link navigation

### ISSUE THREAD

**Issue by edarin** [openfisca/legislation-explorer#16]
When you click for the first time on a variable you get in spite of the top of the page (at the beginning) to the end of the page

**Comment by cbenz** [comment]
See https://github.com/ReactTraining/react-router/blob/master/docs/API.md#to

> Note: React Router currently does not manage scroll position, and will not scroll to the element corresponding to hash.

Solution: http://stackoverflow.com/a/36906825
