### ISSUE TITLE
Proposal turn on dependabot

### ISSUE THREAD

**Issue by Br3nda** [openfisca/legislation-explorer#166]
I use @dependabot to quickly send me PRs of security upgrades in package.json
Then the tests can run and generally the fix is low effort.

Let's turn it on here, so we have git master patched quickly after an advisory.

**Comment by MattiSG** [comment]
Thanks @Br3nda for the suggestion! I had a look at https://github.com/ServiceInnovationLab/legislation-explorer/pulls to see the impact of enabling dependabot.

While I am impressed with the bot itself, I am honestly feeling like this would hardly be manageable in the current resource context of this codebase. If I am to spend time updating dependencies, I would rather spend it removing as many as possible, as the whole webpack pipeline for example is out of control.

I at least can't personally commit to handling incoming updates. Is there anyone around @openfisca/core-contributors who could?

**Comment by Br3nda** [comment]
I'll go ahead and configure it. If there are good enough tests, then it can be a very low effort - certainly less effort than patching manually.

**Comment by Br3nda** [comment]
ah, i don't have access to add app to an organisation. someone will need to do it. 
https://github.com/marketplace/dependabot

**Comment by Br3nda** [comment]
@maukoquiroga You can configure it to just do security patches - and also to just do lock file changes.

**Comment by maukoquiroga** [comment]
I did:

<img width="703" alt="capture d ecran 2018-08-20 a 15 11 08" src="https://user-images.githubusercontent.com/329236/44342451-521f6a00-a48b-11e8-9f03-eb21770b0569.png">
<img width="505" alt="capture d ecran 2018-08-20 a 15 10 50" src="https://user-images.githubusercontent.com/329236/44342453-521f6a00-a48b-11e8-86d0-53a3ff69f906.png">

Do you think we can close the issue?
