### ISSUE TITLE
Isolate tests from any live environment.

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/legislation-explorer#170]
In order to not depend on the state of the live openfisca-france public api to pass the test, we need to update our testing procedure.
- Should we keep using the openfisca-france web-api ?
- Should we use the lastet country template web-api ?

**Comment by MattiSG** [comment]
It is clear to me we should switch to the country template. It is already used as a demonstrator, reinforcing its central “tutorial” usage seems to me to be a good way to consolidate best practices.

In the long term, the Core OpenFisca team should be responsible for managing shared elements, not any country's.

I thus feel we should have something like `demo.openfisca.org` that should be the same as two-letter country code subdomains, with the country template.
