### ISSUE TITLE
Parameters have no callers

### ISSUE THREAD

**Issue by edarin** [openfisca/legislation-explorer#19]
The attribut "Formules utilisant ce paramètre" is always missing.

[Example](https://legislation.openfisca.fr/parameters/al.R2.taux3_dom)

**Comment by cbenz** [comment]
Thanks @edarin 
This is related to https://github.com/openfisca/openfisca-parsers/issues/19

**Comment by MattiSG** [comment]
The example is now a dead link.

Here's what happens:
![capture d ecran 2017-01-24 a 19 09 51](https://cloud.githubusercontent.com/assets/222463/22260314/1d31e312-e269-11e6-9a06-b13c10a9c99b.png)

**Comment by cbenz** [comment]
#43 removed the field, but we'll have to re-add it later.

**Comment by MattiSG** [comment]
The field has been removed, there are many other information that could be shown. Issues are not here to list all possibilities, but to represent validated user needs. Closing until we have documented use cases for this element.
