### ISSUE TITLE
Style error on landing page first load

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/legislation-explorer#199]
`.loading` CSS rule should not be applied to the list of parameters and variables:

<img width="1440" alt="capture d ecran 2018-10-02 a 18 24 16" src="https://user-images.githubusercontent.com/329236/46362383-6badf700-c670-11e8-8af7-f64679768bea.png">

## Reproduce it locally

Set your `nginx` config to something like this:

```
http {
  upstream legislation-explorer {
    server localhost:2030;
  }

  server {
    listen      80;
    server_name localhost;

    location ~/legislation(.*)$ {
        proxy_pass http://legislation-explorer$1;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
```

Then run:

```
npm install
npm run clean
npm run build
npm start
```

And visit `http://localhost/legislation`

**Comment by fpagnoux** [comment]
This is _really_ weird:

For the [France instance](https://fr.openfisca.org/legislation/), I **cannot** reproduce the bug for:
- Chrome 69
- Safari 12 
- Firefox 62

Incognito mode doesn't change anything.

However, for the new [Demo instance](http://demo.openfisca.org/legislation), I experience the bug will all the exact same browsers 😲 .

The two instances are served by the same version of the legislation explorer, with the same version of node, and have the same `package-lock.json`.

Even weirder, others (@sandcha, @maukoquiroga) experience the bug on the France instance too 😱

**Comment by fpagnoux** [comment]
More strangeness:

Going  to a variable page, and coming back to the home page, seems to temporarily fix the issue.

This seem not fully deterministic...
