### ISSUE TITLE
Wrong request url in swagger

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/legislation-explorer#209]
For example:

<img width="1116" alt="capture d ecran 2018-10-16 a 17 33 15" src="https://user-images.githubusercontent.com/329236/47028444-b5ff9f80-d169-11e8-97a5-18198fbb6a43.png">

**Comment by Morendil** [comment]
Side effect of #205 ?

**Comment by fpagnoux** [comment]
Fixed by https://github.com/openfisca/openfisca-core/pull/745
