### ISSUE TITLE
Formula is not always updated

### ISSUE THREAD

**Issue by benjello** [openfisca/legislation-explorer#21]
When clicking on on Formules utilisant cette variable or Variables utilisées, the code source is nbot updated

**Comment by pnbt** [comment]
Ok, il suffit qu'on appelle la fonction:

parent.fetch_graph_for_variable('revdisp')
​
Christophe, tu sais ou il faut mettre ce call dans le framework react?

**Comment by cbenz** [comment]
@pnbt @benjello I think you adressed different problems but quite similar though!
