### ISSUE TITLE
Filter variables based on their label

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#23]
As a reuser,
I can search for a term in the label of variables,
To identify a specific variable

 - - - -

Look for strict inclusion of the looked for substring in the variable name.

Extends #22.

**Comment by MattiSG** [comment]
Needs [accent-folding](http://alistapart.com/article/accent-folding-for-auto-complete) support.

**Comment by cbenz** [comment]
Didn't we agree on doing a naive and strict substring inclusion?

Could accent-folding be a new issue?

**Comment by MattiSG** [comment]
Ok, you're right, it definitely could. What I meant is I'd rather split across delivering #22, and then #23 with accent-folding, over #22+#23, and then accent-folding.
