### ISSUE TITLE
Track pageviews

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#25]
As a product manager,
I can track pageviews on the legislation explorer,
To follow the efficiency of the search feature

**Comment by MattiSG** [comment]
Use the Piwik instance of data.gouv.fr.

**Comment by cbenz** [comment]
Deployed on https://legislation.openfisca.fr/

Analytics can be seen here:
http://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=yesterday&segment=pageUrl%3D%40legislation.openfisca.fr#?module=Dashboard&action=embeddedIndex&idSite=4&period=day&date=yesterday&idDashboard=1&segment=pageUrl%3D@legislation.openfisca.fr

**Comment by MattiSG** [comment]
Example for [today](http://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=4&period=day&date=2017-01-31&segment=pageUrl%3D%40legislation.openfisca.fr#?module=Dashboard&action=embeddedIndex&idSite=4&period=day&date=2017-01-31&idDashboard=1&segment=pageUrl%3D@legislation.openfisca.fr), first day with actual tracking 🎉
