### ISSUE TITLE
Merge variables and parameters

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#39]
As a Producer,
I don't have to choose between searching within variables and parameters.

**Comment by MattiSG** [comment]
- Use two trees (or one tree with two root nodes).
- Remove the block “Paramètres de la législation”.
- Rename the block “Variables”.
- Ensure the search bar works for all items.
- Ensure the tree layout works for the parameters.

**Comment by cbenz** [comment]
Replaced by #40
