### ISSUE TITLE
No default value for input variable

### ISSUE THREAD

**Issue by laem** [openfisca/legislation-explorer#4]
http://legislation.openfisca.fr/variables/redevable_taxe_apprentissage

![selection_193](https://cloud.githubusercontent.com/assets/1177762/10879513/b79b112a-8154-11e5-8a8c-74eea535984b.png)
When you click on that line link : 

![selection_194](https://cloud.githubusercontent.com/assets/1177762/10879562/ed300e8a-8154-11e5-9ff3-d2faa838cd6e.png)

**Comment by cbenz** [comment]
Good one!

**Comment by cbenz** [comment]
@laem Is this issue still relevant? I don't think so, but I'm not sure I understand it very well now.

**Comment by laem** [comment]
Looks like it's been fixed :tada:
