### ISSUE TITLE
Redesign home page

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#40]
- [x] Add the logo.
- [x] Integrate source version under the logo.
- [x] Count total visible formulas & parameters as a description of the system: `OpenFisca référence {{ count }} formules et {{ count }} paramètres qui modélisent le système socio-fiscal français.`.
- [x] Remove breadcrumbs bar.
- [x] Remove the graph link.
- [x] Remove the nav bar.
- [x] Increase readability of list items: title is variable name, description is its label.
- [x] Make everything bigger.
- [x] Remove direct links to GitHub.

**Comment by MattiSG** [comment]
![img_4687](https://cloud.githubusercontent.com/assets/222463/22594480/865560aa-ea23-11e6-99a5-df8c8b1ca0f0.JPG)
![img_4688](https://cloud.githubusercontent.com/assets/222463/22594481/86721db2-ea23-11e6-8a2f-08a4294deb27.JPG)

The filtering algorithm is **NOT** part of _this_ issue.

**Comment by cbenz** [comment]
Deployed in production (automatically!): https://legislation.openfisca.fr/
