### ISSUE TITLE
Restrict search to variable or parameters

### ISSUE THREAD

**Issue by benjello** [openfisca/legislation-explorer#55]
As user I want to look for a variable and I do not want to be distracted by the parameter (and vice-versa).
I should be able to restrict my search accordingly.

**Comment by MattiSG** [comment]
Hi @benjello, super interesting! Could you please elaborate a bit on a specific case where you are looking for, say, a parameter, what you input in the search field, what you obtain as a result, what you would have liked to obtain and why it is a problem? 😃

If you come to the demonstration tomorrow, it will be a good place to discuss this too.

**Comment by benjello** [comment]
Je passe ne français par facilité et par spécificité, s'il faut faire ce genre de retour en anglais let me know.

 - Je suis à la recherche du taux de cotisation maladie.
 - Je tape maladie, j'ai plein de résultats. Le premier est la cotisation accident du travail et maladie professionnelle mais moi je cherche un taux bien précis de la législation qui est en fait très bas.
 - Je rajoute taux dans ma requête, je n'est plus rien. 
 - Le problème ici est aussi que taux, tranche, barème font référence à des éléments encodés dans les objets idoines de la législation qu'il faut utiliser dans le moteur de recherche. 
 - Comme je sais que je cherchais un paramètre précis, en filtrant sur les paramètres législatifs j'aurai pu préciser ma recherche.
 - Enfin les variables et les paramètres n'ont pas le même statut. Les premiers découle d'un choix des modélisateurs d'openfisca, les autres sont plus des références de valeurs apparaissant dans les textes de lois. Certains utilisateurs ne venant cherchés que ces derniers risquent d'être déroutés.

**Comment by MattiSG** [comment]
Ok, merci beaucoup pour ces détails !

It’s indeed better to stick to English for tools that are international, as opposed to country-specific stuff such as `openfisca-france`, but it’s fine here, this user interview could have been done through other channels in French as well, and it’s still better for it to be public, even if it's in French  :wink:

**Comment by Morendil** [comment]
Closing this as stale. Also, possibly better handled by taking a more "whole picture" approach to who the Legislation Explorer is intended to serve, and how to serve these needs better.
