### ISSUE TITLE
Load legislation parameters from the parameters v2 web API

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#69]
Get parameters list from the prerelease API endpoint.

The barèmes won't have values for the moment, that's ok.

**Comment by cbenz** [comment]
The problem on which we spent a couple of hours with @fpagnoux is already described here: https://github.com/corydolphin/flask-cors/issues/147

I [commented](https://github.com/corydolphin/flask-cors/issues/147#issuecomment-289539799) to give a solution we found.

**Comment by fpagnoux** [comment]
I reproduced the issue without `flask_cors`, and even without CORS header.  `flask_cors` is innocent.
