### ISSUE TITLE
A value of 0 is presented as a removal from legislation

### ISSUE THREAD

**Issue by cbenz** [openfisca/legislation-explorer#74]
On https://legislation.openfisca.fr/impot_revenu.autre.finpfl

![image](https://cloud.githubusercontent.com/assets/12686/24858419/906a498c-1dec-11e7-8895-d9cc3e61bb78.png)

The API returns a boolean: https://api-test.openfisca.fr/parameter/impot_revenu.autre.finpfl

But [this condition](https://github.com/openfisca/legislation-explorer/blob/590bb9969db4ab2df8f30fe3a2bf5b234d48f2ab/src/components/parameter.jsx#L430) uses `! value` abusively, which matches the `false`.

> Meta: @fpagnoux @MattiSG What could we do to avoid this from now?

**Comment by MattiSG** [comment]
> What could we do to avoid this from now?

Enforce the use of either `===` or our brain  :wink:

Thanks for pinpointing the failure, the fix will be easy.
