### ISSUE TITLE
Show variables input elasticity

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#78]
As an _analyst_,
I know if I can provide a variable value on a different period than its definition one and how the engine will expand it,
So that I don't get surprises when I request a computation

- - - -

Parse, expose, show and document `set_input` values.

**Comment by Morendil** [comment]
I'm not sure this is advisable in the current state of Variables, cf openfisca/openfisca-core#750. I recommend closing as very much non-trivial in implementation complexity, with high uncertainty as to user value.
