### ISSUE TITLE
Improve readability of variables

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#79]
Design and implement a new view for variables.

- [x] Increase the description font size.
- [x] Update the sentence to (notice bold):

>  Cette [variable]() s'applique aux [entités]() **individu** / **foyer fiscal** / **ménage** / **famille**.
> Elle a une [période de définition]() **d'un mois** / **d'un an** / **qui est l'éternité. Sa valeur est fixe dans le temps**. 
> Sa valeur est **un entier** / **un nombre décimal** / **une date** _(for unmapped types, default to showing them directly)_.
> Sa [valeur par défaut]() est **0** / **0.0** / **01/01/0001**.

- [x] Add a source code link at the end of each formula with name “Modifier cette formule”.
- [x] Rename the source code link to “Modifier ces informations”.
- [x] For variables with no formula, remove title “Formule de calcul” and add the following text to its details:

> Elle n'a pas de formule et n'est donc **pas calculable**. Elle ne peut qu'être fournie en entrée lors d'un calcul.

- [x] Localize all of the textual elements.
- [x] Remove the “external link” icons.

**Comment by MattiSG** [comment]
Fixes #76.

**Comment by Anna-Livia** [comment]
Proposition : 
<img width="340" alt="capture d ecran 2017-07-06 a 15 47 33" src="https://user-images.githubusercontent.com/13916213/27914158-9aab40a8-6262-11e7-9b0f-bbcffcb726ac.png">

**Comment by Anna-Livia** [comment]
Dans le cas des variables dont : 
- la valeur par défaut est 0 
- Le type de la valeur est Float
L'API renvoie "0" et non "0.0" --> Est ce qu'on gère cela au niveau du front ou de l'API ?
