### ISSUE TITLE
Index entities

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#80]
As a _producer_,
I can search for an entity type in the legislation explorer,
So that I can get all necessary information to code formulas in a single place

**Comment by fpagnoux** [comment]
👍 

While training partners, information about **france** entities would have been really helpful.

**Comment by MattiSG** [comment]
The URL scheme is flat just like for variables and parameters: `legislation.openfisca.fr/individu` presents an entity page.

In case there is a naming conflict, the behaviour is undefined and one page or the other could be served. Giving variables, parameters or entities the same name is a bad practice and support for it will be deprecated.
