### ISSUE TITLE
Broken source code links

### ISSUE THREAD

**Issue by Morendil** [openfisca/legislation-explorer#82]
Links displayed in both web pages and JSON data point to the wrong place, example:

```
{
defaultValue: 0,
definitionPeriod: "MONTH",
description: "SMIC proratisé (mensuel)",
entity: "individu",
formulas: {
0001-01-01: {
content: "def function(self, simulation, period): coefficient_proratisation = simulation.calculate('coefficient_proratisation', period) smic_horaire_brut = simulation.legislation_at(period.start).cotsoc.gen.smic_h_b smic_proratise = coefficient_proratisation * smic_horaire_brut * 35 * 52 / 12 return smic_proratise ",
source: "https://github.com/openfisca/openfisca-france/blob/18.2.0ckages/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py#L296-L301"
}
},
id: "smic_proratise",
source: "https://github.com/openfisca/openfisca-france/blob/18.2.0ckages/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py#L290-L301",
valueType: "Float"
}
```

**Comment by MattiSG** [comment]
Thanks for the report!

- [ ] Replace the length-based prefix computation by using the `.__module__` accessor and replacing `.` by `/`.

**Comment by fpagnoux** [comment]
The suggested implementation doesn't work, as variables don't have a `__module__` in the context within which we import them. See https://github.com/openfisca/openfisca-core/pull/502 for an alternative implem.

**Comment by fpagnoux** [comment]
Also, I don't think we should give more than implementation *suggestion* in issues ;)

**Comment by MattiSG** [comment]
> I don't think we should give more than implementation suggestions in issues ;)

This definitely was only a suggestion 🙂

Why was this closed, though? The issue raised by the user is still valid. The fact that the suggested implementation wasn't doesn't mean that the problem disappeared.
