### ISSUE TITLE
Handle multiple words research

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/legislation-explorer#84]
As a legislation explorer user typing "salaire base" in the search field, 
I get the variable "salaire_de_base" in my results

**Comment by MattiSG** [comment]
Should supersede #55 if parameters are properly named.

**Comment by MattiSG** [comment]
1. Select only variables where name contains each query words in either variable name or description.
2. Group variables according to query word match count in variable name and order them in decreasing order.
3. Group variables according to query word match count in variable description and order them in decreasing order.
4. Group each subset according to query word match index sum.
5. Sort each sub-subset according to alphabetical order.
6. Concatenate all sub-subsets and present them as ordered results list.

## Examples

`salaire base` →
- `salaire_de_base` _Salaire de base, en général appelé salaire brut, la 1ère ligne sur la fiche de paie_
- `cotsoc.indemnite_fin_contrat.taux` _Pourcentage du salaire de base_

**Comment by sandcha** [comment]
1 => Every result must cover all query words ; remove results that doesn't.

Besides, query word repetition in a variable/parameter name and description has no influence ; do not change the order/weight of such results.
