### ISSUE TITLE
Replace errors emailing by logging 

### ISSUE THREAD

**Issue by cbenz** [openfisca/legislation-explorer#86]
Some email addresses are hardcoded in the source code: [here](https://github.com/openfisca/legislation-explorer/blob/master/src/server/index.js#L19) and [there](https://github.com/openfisca/legislation-explorer/blob/master/src/server/index.js#L27).

Either:
- disable the whole feature of mail sending when an exception occurs at runtime
- extract the strings to the [config files](https://github.com/openfisca/legislation-explorer/tree/master/config)

**Comment by MattiSG** [comment]
I'm in favour of disabling email. That is an ancient way to log errors, that doesn't provide history nor insight, and doesn't properly support collaboration. Logging should be done in some accessible way though.

**Comment by MattiSG** [comment]
Replace email logging by Piwik events. [Example](https://github.com/sgmap/mes-aides-ui/blob/bcffb6fc2612bb9c987a7c5ce494dbebae6bbe62/app/js/controllers/resultat.js#L32).

**Comment by MattiSG** [comment]
Make Piwik ID & host configurable.

**Comment by MattiSG** [comment]
This kind of logging happens in the backend, not in the frontend. Just use a standard file logger such as https://github.com/winstonjs/winston, which will make it easy to migrate to anything else whenever we desire to.
