### ISSUE TITLE
Do not give the impression that legislation / API switch is a tab toggle

### ISSUE THREAD

**Issue by MattiSG** [openfisca/legislation-explorer#89]
**If I:**

- Search for “smic”.
- Click on “smic_proratise”.
- Click on “API”.
- Click on “Legislation”.

**Then:**

- I am redirected to the homepage.

**While I expected:**

- To be redirected to the “smic_proratise” page, and able to go back to my “smic” research.

**Comment by fpagnoux** [comment]
Other problem that could be solved at the same time:

If I go to a page like [this one](https://legislation.openfisca.fr/aacc_defn), the "Legislation" button is not active.

**Comment by MattiSG** [comment]
Replace “Legislation / API” tabs with two links:

- [Parcourir les 1 472 variables et 1 922 paramètres]() qui modélisent le système socio-fiscal français. _Links to homepage, anchored to the search input._
- [Utiliser l'API]() qui permet de les calculer dans n'importe quel logiciel. _Links to swagger spec._

Move the “En savoir plus” link at the end of the first paragraph.
