### ISSUE TITLE
List enum member names

### ISSUE THREAD

**Issue by guillett** [openfisca/legislation-explorer#95]
Some variables are EnumCol (cf. [rsa_non_calculable in legislation explorer](https://legislation.openfisca.fr/rsa_non_calculable) and [rsa_non_calculable code](https://github.com/openfisca/openfisca-france/blob/18.5.1/openfisca_france/model/prestations/minima_sociaux/rsa.py#L865)).

As a user/consumer:
- I would like to have a better understanding of Enum variables in the legislation explorer.

Currently, I would use those details to validate [a structure in a client application - MesAides](https://github.com/sgmap/mes-aides-ui/blob/master/app/js/constants/droits.js#L156) that add metadata to openfisca variables.

**Comment by benjello** [comment]
Same problem for [allegement_fillon_mode_recouvrement](https://legislation.openfisca.fr/allegement_fillon_mode_recouvrement)

**Comment by MattiSG** [comment]
Thanks for this suggestion @guillett! However, it is not very clear to me what you're suggesting, since this issue is opened in `legislation-explorer` but mentions the API. What is the most important for you: machine access of enum members through the API (and in this case, on which endpoint?), or listing these members in the legislation explorer? 🙂

**Comment by benjello** [comment]
For me it is listing these members in the legislation explorer

**Comment by guillett** [comment]
@MattiSG, the most important for me is the machine access via the API. That is why I created an [new issue](https://github.com/openfisca/openfisca-web-api/issues/137) in `openfisca-web-api`.

Having said that once it is available via the API, I would love to see it in the legislation explorer. 🙂

**Comment by MattiSG** [comment]
- [ ] List all possible names in a table called “Table de correspondance”, along with the associated values. First column is called “Name”, second is called “Code”.
- [ ] Document what is an `enum` type and its usage: “Elle ne peut prendre qu'une valeur chiffrée parmi la liste ci-dessous.”
- [ ] Translate in English and in French.

**Comment by fpagnoux** [comment]
To implement this, we'll need to expose the values of the enum elements in the API.

## Structure

### Suggestion 1

```JSON
{
  "defaultValue": 4, 
  "description": "Activité", 
  "id": "activite", 
  "valueType": "Enum",
  "possibleValues": {
    "Actif occupé": 0,
    "Chômeur": 1,
    "Étudiant, élève": 2,
    "Retraité": 3,
    "Autre inactif": 4
  }
}
```
 
### Suggestion 2

```JSON
{
  "defaultValue": 4, 
  "description": "Activité", 
  "id": "activite", 
  "valueType": "Enum",
  "possibleValues": {
    "0": "Actif occupé",
    "1": "Chômeur",
    "2": "Étudiant, élève",
    "3": "Retraité",
    "4": "Autre inactif"
  }
}
```JSON

## Keyword

Suggestion A: `possibleValues`
Suggestion B: `values`
Suggestion C: `elements`

@guillett @benjello @MattiSG @Anna-Livia @sandcha @Morendil thoughts ?

**Comment by guillett** [comment]
Suggestion D: `members` ?

2 -  D

**Comment by fpagnoux** [comment]
`members` is already used in another context in OpenFisca (the members of an entity).
Plus, is it clear what the members of a variable are ?

**Comment by fpagnoux** [comment]
Or, following swagger style:

### Suggestion 3

```JSON
{
  "defaultValue": 4, 
  "description": "Activité", 
  "id": "activite", 
  "valueType": "String",
  "enum": [
    "Actif occupé",
    "Autre inactif",
    "Chômeur",
    "Étudiant, élève",
    "Retraité"
  ]
}
```

But that notation totally omits the indexes. 
We can make sure the API accepts strings as inputs for enums (instead of ints) but inside OpenFisca, enums values ares integers 🤔 .

**Comment by guillett** [comment]
Note for suggestion 3: It [can](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1) contain `null` for enum like [`statut_marital`](https://github.com/openfisca/openfisca-france/blob/18.7.6/openfisca_france/model/caracteristiques_socio_demographiques/demographie.py#L51-L64) that start at 1

**Comment by Anna-Livia** [comment]
suggestion 3 for the structure, "possibleValues" for the key :)

**Comment by Morendil** [comment]
3 - B

I favor the array representation over the other ones because it communicates an intention of doing the simplest thing, labeling enum values like array indexes - starting at 0, in order and without skipping any values.

**Comment by benjello** [comment]
2-B
